query ($handle: String!) {
  productByHandle(handle: $handle) {
    title
    id
    handle
    description
    descriptionHtml
    availableForSale
    createdAt
    metafields(first: 10) {
      edges {
        node {
          id
          key
          namespace
          value
        }
      }
    }
    images(first: 10) {
      edges {
        node {
          originalSrc
          transformedSrc(maxHeight: 200, maxWidth: 200)
          altText
          id
        }
      }
    }
    options(first: 10) {
      id
      name
      values
    }
    variants(first: 10) {
      edges {
        node {
          id
          title
          sku
          image {
            id
            originalSrc
            altText
            width
            height
          }
          availableForSale
          selectedOptions {
            name
            value
          }
          priceV2 {
            amount
            currencyCode
          }
        }
      }
    }
  }
}
