query($handle: String!) {
  productByHandle(handle: $handle) {
    title
    id
    handle
    images(first: 10) {
        edges {
            node {
                originalSrc
                transformedSrc(maxHeight: 200, maxWidth: 200)
                altText
                id
            }
        }
    }
    variants(first: 1) {
      edges {
        node {
          id
        }
      }
    }
  }
}
